# Configuration for chest exposure analyzer

# Model paths
models:
  yolo_model_path: "weights/yolov11l-pose.pt"
  sam2_model_path: "chest_exposure_analyzer/weights/sam2_hiera_large.pt"
  sam2_model_type: "hiera_large"  # Updated to match SAM2 model types

# Detection parameters
detection:
  confidence_threshold: 0.5
  iou_threshold: 0.45
  max_detections: 10

# Segmentation parameters (SAM2)
segmentation:
  points_per_side: 32
  pred_iou_thresh: 0.88
  stability_score_thresh: 0.95
  crop_n_layers: 0
  crop_n_points_downscale_factor: 1
  min_mask_region_area: 0
  # SAM2 specific parameters
  multimask_output: true
  use_m2m: false

# Chest analysis parameters
analysis:
  chest_triangle_expansion_factor: 1.2
  min_connected_component_area: 100
  morphological_operations: true
  
# Chest exposure detection parameters
exposure_detection:
  min_intersection_ratio: 0.01  # Minimum ratio of intersection to chest area to consider exposed
  min_intersection_area: 100    # Minimum intersection area in pixels to consider exposed
  min_confidence_threshold: 0.5 # Minimum confidence to copy to exposed folder
  save_exposure_analysis: true  # Save exposure analysis visualizations
  
  # Morphological operations for mask refinement
  morphology_kernel_size: 5     # Size of morphological operation kernel
  opening_iterations: 1         # Opening iterations to remove noise
  closing_iterations: 2         # Closing iterations to fill gaps
  
  # Mosaic censoring parameters
  mosaic_block_size: 30         # Size of mosaic blocks in pixels
  mosaic_intensity: 1.0         # Mosaic intensity (1.0 = full mosaic, 0.0 = no effect)
  save_mosaic_comparison: true  # Save before/after mosaic comparison
  
  # Mosaic region expansion parameters
  mosaic_dilation_kernel_size: 10    # Size of dilation kernel to expand mosaic regions
  mosaic_dilation_iterations: 2      # Number of dilation iterations for coverage expansion

# Visualization settings
visualization:
  keypoint_radius: 5
  line_thickness: 2
  alpha_overlay: 0.5
  save_intermediate_steps: true

# I/O paths
paths:
  input_dir: "chest_exposure_analyzer/data/input"
  output_dir: "chest_exposure_analyzer/data/output"
  exposed_dir: "chest_exposure_analyzer/data/output/exposed"
  weights_dir: "weights"